### ISSUE TITLE
npm start fails with ERR_INVALID_URL

### ISSUE THREAD

**Issue by lemire** [ada-url/url-dataset#3]
```
$ npm start

> url-dataset@1.0.0 start
> node --max-old-space-size=8192 --no-warnings lib/index.js

 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/100000TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at new Request (file:///home/dlemire/CVS/github/url-dataset/node_modules/node-fetch/src/request.js:55:16)
    at file:///home/dlemire/CVS/github/url-dataset/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///home/dlemire/CVS/github/url-dataset/node_modules/node-fetch/src/index.js:49:9)
    at worker (file:///home/dlemire/CVS/github/url-dataset/lib/index.js:23:26)
    at asyncWrapper (/home/dlemire/CVS/github/url-dataset/node_modules/fastq/queue.js:213:12)
    at push (/home/dlemire/CVS/github/url-dataset/node_modules/fastq/queue.js:110:14) {
  input: 'https://\n                      youtube.com\n                  ',
  code: 'ERR_INVALID_URL'
}
```

**Comment by anonrig** [comment]
I'm looking into it 👍

**Comment by anonrig** [comment]
Which Node version do you use?

**Comment by anonrig** [comment]
I pushed several commits. Let me know if it works. @lemire
